### ISSUE TITLE
Screenshot?

### ISSUE THREAD

**Issue by forivall** [nerdenough/essence-dark-syntax#1]

**Comment by Goddak** [comment]
Bump @nerdenough, a screenshot would be nice :smiley:

**Comment by oldanderw** [comment]
I would disagree @Goddak, a screenshot is a must for me otherwise i have no idea what it looks like and me and a lot of others are just going to keep moving down the list when looking for a theme

**Comment by nerdenough** [comment]
Closing as package is unmaintained
